x-services:
  fastapi_app: &fastapi_app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env

version: '3.8'
services:
  db:
    image: postgres:15 # 5432
    restart: always
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  web:
    <<: *fastapi_app
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --reload"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data_dev:


