"""

Revision ID: e799a48f016d
Revises: 
Create Date: 2023-04-11 13:50:09.803138

"""
from alembic import op
import sqlalchemy as sa
import src

# revision identifiers, used by Alembic.
revision = 'e799a48f016d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', src.account.types.EmailType(length=255), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('date_joined', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('is_superuser', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('is_staff', sa.Boolean(), server_default='f', nullable=False),
    sa.Column('post_agreement', sa.Boolean(), server_default='t', nullable=False),
    sa.Column('avatar', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_user_email'), 'account_user', ['email'], unique=True)
    op.create_index(op.f('ix_account_user_id'), 'account_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_user_id'), table_name='account_user')
    op.drop_index(op.f('ix_account_user_email'), table_name='account_user')
    op.drop_table('account_user')
    # ### end Alembic commands ###
